agents:
  queue: hosted

secrets:
  - MISE_GITHUB_TOKEN

steps:
  - label: ":hammer: Build"
    key: build
    command: mise run build
    plugins:
      - mise#v1.1.1: ~

  - label: ":test_tube: Test"
    key: test
    command: mise run test
    plugins:
      - mise#v1.1.1: ~

  - label: ":lint-roller: Lint"
    key: lint
    command: mise run lint
    plugins:
      - mise#v1.1.1: ~

  - label: ":mag: Vet"
    key: vet
    command: mise run vet
    plugins:
      - mise#v1.1.1: ~

  - wait

  - label: ":github: Release"
    if: "build.tag != null"
    key: release
    command: .buildkite/steps/release.sh
    plugins:
      - mise#v1.1.1: ~
    secrets:
      GITHUB_TOKEN: GIT_CREDENTIAL_BUILDKITE_OIDC_RELEASE_TOKEN
